### ISSUE TITLE
Installation unfructueuse

### ISSUE THREAD

**Issue by quenenni** [CagetteNet/cagette#133]
Salut,

Je tente l'install sur un Debian 9.

J'ai suivi la docu pour Neko (https://wiki.cagette.net/dev:install_neko), mais quand je vais à la page racine du site, il me liste les ficheirs / dossiers.
J'ai vérifié et le .htaccess est bien présent et pris en compte.

Si je vais à la page /install ou /user/login/, j'ai l'erreur:
```
Uncaught exception - load.c(181) : Module not found : /var/www/cagette/www/index
```

J'ai testé que Neko fonctionnait bien.
J'ai créé un petit fichier et l'ai compilé pour avoir la version .n qui est reconnue et affiche mon msg dans le navigateur.
Je n'ai donc pas l'impression que c'est neko le problème.

Rien dans les logs d'apache.

J'ai aussi exécuté le commande cron pour voir ce que cela donnait:
```
(cd /var/www/cagette/www/ && neko index.n cron/minute)
Uncaught exception - load.c(181) : Module not found : index.n
```
J'ai mis debug="1" dans config.xml comme proposé dans la Faq, mais ça n'a rien changé.

Avec tout ça, je ne comprend pas pourquoi il n'y a pas de ficheir index.n dans le dossier www de cagette (ni aucun autre ficheir .n)

Est-ce que je suis censé compiler cagette avec nekoc pour avoir ce fichier index.n?
Je ne vois rien en ce sens dans le guide.

PS: sous debian 9, 
```
apt-get install libmysqlclient-dev
```
n'existe pas. Il faut ceci:
```
apt install default-libmysqlclient-dev
```

**Comment by quenenni** [comment]
J'ai trouvé dans un ticket fermé (https://github.com/bablukid/cagette/issues/92) l'info comme quoi de fait, vu que je l'ai aussi téléchargé du dépôt git (pas de version compilée dispo), il fallait compiler l'appli.

J'ai suivi ce guide https://wiki.cagette.net/dev:compile

- Dans projBack:

  * make compile -> ok

- Dans projFront

  * npm install ->  se termine par une erreur:
```
...
make : on quitte le répertoire « /var/www/cagette/projFront/node_modules/node-sass/build »
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/cagette/projFront/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/var/www/cagette/projFront/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/cagette/projFront/node_modules/node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
que j'ai pu passer en changeant la version de node-sass à 4.12.0 (dans le fichier package.json).

  * j'ai ajouté ces 2 commandes car npm me disait que je devais le faire manuellement:
```
npm install acorn@^6.0.0
npm install react@^16.6.3
```

  * npm run libs:dev -> Ok
  * npm run libs:prod -> Ok
  * npm run build:js -> se termine par une erreur.
```
# npm run build:js

> cagette.net@ build:js /var/www/cagette/projFront
> haxe cagetteJs.hxml

/var/www/cagette/projFront/.haxelib/redux/0,5,2/redux/macro/ReduxMacro.hx:8: characters 2-44 : Cannot access private field addBuilder
?:1: characters 1-7 : Build failure
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cagette.net@ build:js: `haxe cagetteJs.hxml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cagette.net@ build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-14T20_37_56_363Z-debug.log
```
et le contenu du fichier /root/.npm/_logs/2019-11-14T20_37_56_363Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:js' ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prebuild:js', 'build:js', 'postbuild:js' ]
5 info lifecycle cagette.net@~prebuild:js: cagette.net@
6 info lifecycle cagette.net@~build:js: cagette.net@
7 verbose lifecycle cagette.net@~build:js: unsafe-perm in lifecycle true
8 verbose lifecycle cagette.net@~build:js: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/cagette/projFront/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle cagette.net@~build:js: CWD: /var/www/cagette/projFront
10 silly lifecycle cagette.net@~build:js: Args: [ '-c', 'haxe cagetteJs.hxml' ]
11 silly lifecycle cagette.net@~build:js: Returned: code: 1  signal: null
12 info lifecycle cagette.net@~build:js: Failed to exec build:js script
13 verbose stack Error: cagette.net@ build:js: `haxe cagetteJs.hxml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid cagette.net@
15 verbose cwd /var/www/cagette/projFront
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:js"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error cagette.net@ build:js: `haxe cagetteJs.hxml`
22 error Exit status 1
23 error Failed at the cagette.net@ build:js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Une idée du problème?

**Comment by bablukid** [comment]
Bonjour, je suis désolé j'ai fait pas mal de changements ces derniers temps... il faudra que je refasse la page d'installation.    Tu t'en es sorti ou pas ?

**Comment by quenenni** [comment]
Point réussi, non.

Il me semble que l'erreur vient de cette ligne
```
/var/www/cagette/projFront/.haxelib/redux/0,5,2/redux/macro/ReduxMacro.hx:8: characters 2-44 : Cannot access private field addBuilder
```

J'ai été voir le fichier `/var/www/cagette/projFront/.haxelib/redux/0,5,2/redux/macro/ReduxMacro.hx` et essayé de remonter le problème, mais j'ai abandonné.
